version: 0
schema: Custom.AdminDashAccess.V1
parser:
  fastmatch:
    # Define an array of patterns to match against.
    # In this example we only use one pattern because the log format is the same for all lines.
    # If we wanted to include the Apache Extended Log format, we could provide an additional pattern.
    match:
      - '%{remote_ip} %{source} [%{log_level}] [%{timestamp}] %{user} - %{message}'
    emptyValues: [ ] # specify that `-` string values are considered null
fields:
  - name: remote_ip
    type: string
    indicators:
      - ip
  - name: source
    type: string
  - name: log_level
    type: string
  - name: timestamp
    type: timestamp
    isEventTime: true
    timeFormat: rfc3339
  - name: user
    type: string
  - name: message
    type: string